version: '3.1'
services:
  postgres:
    image: "postgres:alpine"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tp_bases
    ports:
      - 8082:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres


